Repository IrisShaders/Iris, pull requests merged in 2021-12, with the labels that each got.

#1039 Update Polish translation (pl_pl)
  src/main/resources/assets/iris/lang/pl_pl.json
Labels: type: translations

#1046 Update zh_cn translations
  src/main/resources/assets/iris/lang/zh_cn.json
Labels: type: translations

#1075 Update zh_tw.json
  src/main/resources/assets/iris/lang/zh_tw.json
Labels: type: translations

#1067 Add action oriented auto releases for all platforms
  .github/workflows/build-release.yml
  build.gradle
Labels: enhancement, code quality

#980 Add FAQ section to README.md
  README.md
  docs/faq.md
  docs/supportedshaders.md
Labels: documentation, enhancement, status: waiting on review

#1085 Installation and usage guide
  docs/guide-resources/check.png
  docs/guide-resources/fabricinstaller.png
  docs/guide-resources/fabricprofile.png
  docs/guide-resources/fabricsuccess.png
  docs/guide-resources/installer.png
  docs/guide-resources/launcherprompt.png
  docs/guide-resources/menuingame.jpg
  docs/guide-resources/profile.png
  docs/guide-resources/shaderpacksmenu.png
  docs/guide-resources/success.png
  docs/guide-resources/videosettings.png
  docs/guide.md
Labels: documentation

#917 Use RenderSystem and GlStateManager instead of direct GL calls when possible
  src/main/java/net/coderbot/iris/gl/IrisRenderSystem.java
  src/main/java/net/coderbot/iris/gl/framebuffer/GlFramebuffer.java
  src/main/java/net/coderbot/iris/gl/image/ImageBinding.java
  src/main/java/net/coderbot/iris/gl/image/ImageLimits.java
  src/main/java/net/coderbot/iris/gl/program/Program.java
  src/main/java/net/coderbot/iris/gl/program/ProgramBuilder.java
  src/main/java/net/coderbot/iris/gl/program/ProgramImages.java
  src/main/java/net/coderbot/iris/gl/program/ProgramSamplers.java
  src/main/java/net/coderbot/iris/gl/program/ProgramUniforms.java
  src/main/java/net/coderbot/iris/gl/sampler/SamplerLimits.java
  src/main/java/net/coderbot/iris/gl/shader/GlShader.java
  src/main/java/net/coderbot/iris/gl/shader/ProgramCreator.java
  src/main/java/net/coderbot/iris/gl/shader/StandardMacros.java
  src/main/java/net/coderbot/iris/gl/uniform/FloatUniform.java
  src/main/java/net/coderbot/iris/gl/uniform/IntUniform.java
  src/main/java/net/coderbot/iris/gl/uniform/JomlMatrixUniform.java
  src/main/java/net/coderbot/iris/gl/uniform/MatrixFromFloatArrayUniform.java
  src/main/java/net/coderbot/iris/gl/uniform/MatrixUniform.java
  src/main/java/net/coderbot/iris/gl/uniform/Vector2IntegerJomlUniform.java
  src/main/java/net/coderbot/iris/gl/uniform/Vector2Uniform.java
  src/main/java/net/coderbot/iris/gl/uniform/Vector3Uniform.java
  src/main/java/net/coderbot/iris/gl/uniform/Vector4Uniform.java
  src/main/java/net/coderbot/iris/pipeline/DeferredWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/pipeline/ShadowRenderer.java
  src/main/java/net/coderbot/iris/postprocess/CenterDepthSampler.java
  src/main/java/net/coderbot/iris/postprocess/CompositeRenderer.java
  src/main/java/net/coderbot/iris/postprocess/FinalPassRenderer.java
  src/main/java/net/coderbot/iris/postprocess/FullScreenQuadRenderer.java
  src/main/java/net/coderbot/iris/rendertarget/DepthTexture.java
  src/main/java/net/coderbot/iris/rendertarget/FramebufferBlitter.java
  src/main/java/net/coderbot/iris/rendertarget/NativeImageBackedCustomTexture.java
  src/main/java/net/coderbot/iris/rendertarget/NoiseTexture.java
  src/main/java/net/coderbot/iris/rendertarget/RenderTarget.java
  src/main/java/net/coderbot/iris/rendertarget/SingleColorTexture.java
  src/main/java/net/coderbot/iris/samplers/TextureAtlasTracker.java
  src/main/java/net/coderbot/iris/shadows/EmptyShadowMapRenderer.java
  src/main/java/net/coderbot/iris/shadows/ShadowRenderTargets.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/shader_overrides/IrisChunkProgram.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/mixin/shader_overrides/MixinChunkProgram.java
Labels: enhancement, status: waiting on review

#1080 Modernize ShadowRenderer for 1.17
  src/main/java/net/coderbot/iris/pipeline/DeferredWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/pipeline/ShadowRenderer.java
  src/main/java/net/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/shadows/ShadowRenderingState.java
Labels: version: 1.17, status: waiting on review

#1094 The big 1.17 cleanup - part one
  gradle.properties
  src/main/java/net/coderbot/iris/Iris.java
  src/main/java/net/coderbot/iris/gl/IrisRenderSystem.java
  src/main/java/net/coderbot/iris/gl/framebuffer/GlFramebuffer.java
  src/main/java/net/coderbot/iris/gl/shader/ProgramCreator.java
  src/main/java/net/coderbot/iris/gl/shader/StandardMacros.java
  src/main/java/net/coderbot/iris/mixin/MixinGameRenderer.java
  src/main/java/net/coderbot/iris/mixin/MixinLevelRenderer.java
  src/main/java/net/coderbot/iris/mixin/texunits/MixinBufferVertexConsumer.java
  src/main/java/net/coderbot/iris/mixin/texunits/MixinDefaultVertexFormat.java
  src/main/java/net/coderbot/iris/mixin/texunits/MixinGlStateManager.java
  src/main/java/net/coderbot/iris/mixin/texunits/MixinLightTexture.java
  src/main/java/net/coderbot/iris/mixin/texunits/MixinOverlayTexture.java
  src/main/java/net/coderbot/iris/mixin/vertices/block_rendering/MixinChunkRebuildTask.java
  src/main/java/net/coderbot/iris/pipeline/ShadowRenderer.java
  src/main/java/net/coderbot/iris/pipeline/newshader/ExtendedShader.java
  src/main/java/net/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/vertices/IrisVertexFormats.java
  src/main/resources/fabric.mod.json
  src/main/resources/mixins.iris.json
Labels: version: 1.17, status: waiting on author

#967 Prefix vanilla attributes with iris_ on 1.17
  src/main/java/net/coderbot/iris/mixin/MixinShaderInstance.java
  src/main/java/net/coderbot/iris/pipeline/newshader/TriforcePatcher.java
Labels: version: 1.17, status: waiting on review

#1101 Implement the rain.depth property
  src/main/java/net/coderbot/iris/mixin/MixinLevelRenderer.java
  src/main/java/net/coderbot/iris/pipeline/DeferredWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/pipeline/FixedFunctionWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/pipeline/WorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/shaderpack/PackDirectives.java
Labels: status: waiting on author

#1103 Triforce consolidation 2
  src/main/java/net/coderbot/iris/pipeline/SodiumTerrainPipeline.java
  src/main/java/net/coderbot/iris/pipeline/newshader/NewShaderTests.java
  src/main/java/net/coderbot/iris/pipeline/newshader/TriforceCompositePatcher.java
  src/main/java/net/coderbot/iris/pipeline/newshader/TriforcePatcher.java
  src/main/java/net/coderbot/iris/pipeline/newshader/TriforceSodiumPatcher.java
  src/main/java/net/coderbot/iris/postprocess/CompositeRenderer.java
  src/main/java/net/coderbot/iris/postprocess/FinalPassRenderer.java
Labels: code quality, status: waiting on review
