Repository IrisShaders/Iris, pull requests merged in 2021-11, with the labels that each got.

#907 Update it_it.json
  src/main/resources/assets/iris/lang/it_it.json
Labels: type: translations

#879 Add missing translations to `de_de.json`
  src/main/resources/assets/iris/lang/de_de.json
Labels: type: translations

#909 Hand Rendering
  src/main/java/net/coderbot/iris/layer/GbufferProgram.java
  src/main/java/net/coderbot/iris/layer/GbufferPrograms.java
  src/main/java/net/coderbot/iris/mixin/GameRendererAccessor.java
  src/main/java/net/coderbot/iris/mixin/MixinGameRenderer.java
  src/main/java/net/coderbot/iris/mixin/MixinItemInHandRenderer.java
  src/main/java/net/coderbot/iris/mixin/MixinLevelRenderer.java
  src/main/java/net/coderbot/iris/mixin/rendertype/MixinRenderType.java
  src/main/java/net/coderbot/iris/pipeline/DeferredWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/pipeline/FixedFunctionWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/pipeline/HandRenderer.java
  src/main/java/net/coderbot/iris/pipeline/WorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/rendertarget/RenderTargets.java
  src/main/java/net/coderbot/iris/samplers/IrisSamplers.java
  src/main/resources/mixins.iris.json
Labels: enhancement, target: next release

#986 Fix alpha cutoff
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/mixin/shader_overrides/MixinBlockRenderPass.java
  src/sodiumCompatibility/resources/mixins.iris.compat.sodium.json
Labels: bug in sodium

#989 Better Mod Compatibility With Hand Rendering
  src/main/java/net/coderbot/iris/mixin/GameRendererAccessor.java
  src/main/java/net/coderbot/iris/mixin/MixinGameRenderer.java
  src/main/java/net/coderbot/iris/pipeline/HandRenderer.java
Labels: enhancement, mod compatibility

#994 Replace Sodium sky Mixin with custom one
  src/main/resources/fabric.mod.json
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/mixin/sky/MixinLevelRenderer.java
  src/sodiumCompatibility/resources/mixins.iris.compat.sodium.json
Labels: bug in sodium

#1004 Separate shader patching from SodiumTerrainPipeline init, use vertex type info in patching
  src/main/java/net/coderbot/iris/pipeline/SodiumTerrainPipeline.java
  src/main/java/net/coderbot/iris/pipeline/newshader/TriforceSodiumPatcher.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/shader_overrides/IrisChunkProgramOverrides.java
Labels: high priority, version: 1.17, target: next release

#880 Add lolcat language (lol_us.json)
  src/main/resources/assets/iris/lang/lol_us.json
Labels: type: translations

#840 Update Russian language for Iris 1.1.2
  src/main/resources/assets/iris/lang/ru_ru.json
Labels: type: translations

#833 Update Russian language for trunk branch
  src/main/resources/assets/iris/lang/ru_ru.json
Labels: type: translations

#1001 Add Slovak language
  src/main/resources/assets/iris/lang/sk_sk.json
Labels: type: translations

#888 translate pt_br from scratch
  src/main/resources/assets/iris/lang/pt_br.json
Labels: type: translations

#993 Update German translation
  src/main/resources/assets/iris/lang/de_de.json
Labels: type: translations

#903 Update et_ee.json
  src/main/resources/assets/iris/lang/et_ee.json
Labels: type: translations

#902 Update ru_ru.json
  src/main/resources/assets/iris/lang/ru_ru.json
Labels: type: translations

#901 Update zh_tw.json
  src/main/resources/assets/iris/lang/zh_tw.json
Labels: type: translations

#885 Update zh_cn translation
  src/main/resources/assets/iris/lang/zh_cn.json
Labels: type: translations

#856 Updated Persian/Farsi translations
  src/main/resources/assets/iris/lang/fa_ir.json
Labels: type: translations

#904 Use ModifyVariable for entity list sorting
  src/main/java/net/coderbot/batchedentityrendering/mixin/MixinLevelRenderer_EntityListSorting.java
Labels: mod compatibility, target: next release

#975 Custom texture support
  src/main/java/net/coderbot/iris/gl/program/ProgramSamplers.java
  src/main/java/net/coderbot/iris/pipeline/CustomTextureManager.java
  src/main/java/net/coderbot/iris/pipeline/DeferredWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/pipeline/ShadowRenderer.java
  src/main/java/net/coderbot/iris/postprocess/CompositeRenderer.java
  src/main/java/net/coderbot/iris/postprocess/FinalPassRenderer.java
  src/main/java/net/coderbot/iris/rendertarget/NativeImageBackedCustomTexture.java
  src/main/java/net/coderbot/iris/samplers/IrisSamplers.java
  src/main/java/net/coderbot/iris/shaderpack/CustomTexture.java
  src/main/java/net/coderbot/iris/shaderpack/PackDirectives.java
  src/main/java/net/coderbot/iris/shaderpack/PackRenderTargetDirectives.java
  src/main/java/net/coderbot/iris/shaderpack/ProgramDirectives.java
  src/main/java/net/coderbot/iris/shaderpack/ShaderPack.java
  src/main/java/net/coderbot/iris/shaderpack/ShaderProperties.java
  src/main/java/net/coderbot/iris/shaderpack/texture/CustomTextureData.java
Labels: enhancement
