Repository IrisShaders/Iris, pull requests merged in 2021-08, with the labels that each got.

#696 Fix overlay texture unit, fixes hit flash without shaders
  src/main/java/net/coderbot/iris/texunits/TextureUnit.java
Labels: high priority

#425 Immersive Portals Compatibility
  jitpack.yml
  src/main/java/net/coderbot/iris/mixin/MixinMinecraftClient.java
  src/main/java/net/coderbot/iris/pipeline/PipelineManager.java
  src/main/resources/mixins.iris.json
Labels: target: next release

#762 added Korean Translations (kr_kr)
  src/main/resources/assets/iris/lang/kr_kr.json
Labels: type: translations

#731 Add Turkish translation
  src/main/resources/assets/iris/lang/tr_tr.json
Labels: type: translations

#716 Add Polish translation (pl_pl)
  src/main/resources/assets/iris/lang/pl_pl.json
Labels: type: translations

#485 Added swiss german translations
  src/main/resources/assets/iris/lang/de_ch.json
Labels: type: translations

#467 Estonian translation
  src/main/resources/assets/iris/lang/et_ee.json
Labels: type: translations

#624 Physics Mod compatibility, alongside mod loading checks.
  src/main/java/net/coderbot/iris/Iris.java
  src/main/java/net/coderbot/iris/mixin/MixinDebugHud.java
  src/main/java/net/coderbot/iris/mixin/MixinLivingEntityRenderer.java
  src/main/java/net/coderbot/iris/mixin/gui/MixinInGameHud.java
Labels: high priority, target: next release

#742 Add new Sodium incompatibility screen
  src/main/java/net/coderbot/iris/Iris.java
  src/main/java/net/coderbot/iris/mixin/MixinTitleScreen.java
  src/main/resources/assets/iris/lang/en_us.json
  src/main/resources/mixins.iris.json
Labels: high priority, target: next release
