Repository IrisShaders/Iris, pull requests merged in 2021-09, with the labels that each got.

#750 Add fallback path in case the atlassize didn't get stored
  src/main/java/net/coderbot/iris/mixin/MixinSpriteAtlasTexture.java
Labels: target: next release

#891 Remove duplicate draw call
  src/main/java/net/coderbot/batchedentityrendering/mixin/MixinLevelRenderer.java
  src/main/java/net/coderbot/iris/mixin/MixinLevelRenderer.java
Labels: high priority

#868 Add code for registering Iris-exclusive defines and uniforms
  src/main/java/net/coderbot/iris/gl/program/ProgramBuilder.java
  src/main/java/net/coderbot/iris/gl/shader/StandardMacros.java
  src/main/java/net/coderbot/iris/uniforms/CommonUniforms.java
  src/main/java/net/coderbot/iris/uniforms/IrisExclusiveUniforms.java
Labels: enhancement
