Repository IrisShaders/Iris, pull requests merged in 2022-07, with the labels that each got.

#1394 cameraType Iris exclusive uniform
  src/main/java/net/coderbot/iris/uniforms/IrisExclusiveUniforms.java
Labels: enhancement, status: waiting on review

#1504 Shadow internal format, clear and clear color support
  src/main/java/net/coderbot/iris/pipeline/ClearPass.java
  src/main/java/net/coderbot/iris/pipeline/ClearPassCreator.java
  src/main/java/net/coderbot/iris/pipeline/DeferredWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/shaderpack/PackShadowDirectives.java
  src/main/java/net/coderbot/iris/shadows/ShadowRenderTargets.java
Labels: status: waiting on review

#1501 Add at_midBlock support
  src/main/java/net/coderbot/iris/block_rendering/MaterialIdHolder.java
  src/main/java/net/coderbot/iris/gl/shader/ProgramCreator.java
  src/main/java/net/coderbot/iris/mixin/vertices/MixinBufferBuilder.java
  src/main/java/net/coderbot/iris/mixin/vertices/block_rendering/MixinChunkRebuildTask.java
  src/main/java/net/coderbot/iris/pipeline/DeferredWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/vertices/BlockSensitiveBufferBuilder.java
  src/main/java/net/coderbot/iris/vertices/ExtendedDataHelper.java
  src/main/java/net/coderbot/iris/vertices/IrisVertexFormats.java
  src/main/java/net/coderbot/iris/vertices/NormalHelper.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/IrisChunkShaderBindingPoints.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/block_context/BlockContextHolder.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/block_context/ChunkBuildBuffersExt.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/block_context/ContextAwareVertexWriter.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/block_id/MaterialIdAwareVertexWriter.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/shader_overrides/IrisChunkProgramOverrides.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/IrisChunkMeshAttributes.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/entity_xhfp/EntityVertexBufferWriterNio.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/entity_xhfp/EntityVertexBufferWriterUnsafe.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/terrain_xhfp/XHFPModelVertexBufferWriterNio.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/terrain_xhfp/XHFPModelVertexBufferWriterUnsafe.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/terrain_xhfp/XHFPModelVertexType.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/mixin/block_id/MixinChunkBuildBuffers.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/mixin/block_id/MixinChunkRenderRebuildTask.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/mixin/vertex_format/MixinChunkMeshAttribute.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/mixin/vertex_format/MixinGlVertexFormatBuilder.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/mixin/vertex_format/MixinMultidrawChunkRenderBackend.java
Labels: enhancement
