Repository IrisShaders/Iris, pull requests merged in 2022-03, with the labels that each got.

#1301 Entity XHFP vertex format
  src/main/java/net/coderbot/iris/mixin/vertices/MixinBufferBuilder.java
  src/main/java/net/coderbot/iris/pipeline/ShadowRenderer.java
  src/main/java/net/coderbot/iris/vertices/IrisVertexFormats.java
  src/main/resources/mixins.iris.json
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/IrisModelVertexFormats.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/NormalHelper.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/QuadView.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/entity_xhfp/QuadViewEntity.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/entity_xhfp/writer/EntityVertexBufferWriterNio.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/entity_xhfp/writer/EntityVertexBufferWriterUnsafe.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/terrain_xhfp/QuadViewTerrain.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/terrain_xhfp/XHFPModelVertexBufferWriterNio.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/terrain_xhfp/XHFPModelVertexType.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/xhfp/QuadView.java
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/mixin/vertex_format/entity/MixinQuadVertexType.java
  src/sodiumCompatibility/resources/mixins.iris.compat.sodium.json
Labels: high priority, performance

#1300 Update Korean translation
  src/main/resources/assets/iris/lang/ko_kr.json
Labels: type: translations

#1313 Add finnish language support
  src/main/resources/assets/iris/lang/fi_fi.json
Labels: type: translations

#1303 Optional LWJGLX debugging toggled via iris.properties + client commands
  buildscript/src/main/java/Buildscript.java
  src/main/java/net/coderbot/iris/Iris.java
  src/main/java/net/coderbot/iris/IrisLogging.java
  src/main/java/net/coderbot/iris/config/IrisConfig.java
  src/main/java/net/coderbot/iris/gl/GLDebug.java
  src/main/resources/assets/iris/lang/en_us.json
Labels: enhancement
