Repository IrisShaders/Iris, pull requests merged in 2022-01, with the labels that each got.

#1139 Add support for the prepare stage
  src/main/java/net/coderbot/iris/pipeline/DeferredWorldRenderingPipeline.java
Labels: status: waiting on author

#1173 Update zh_tw.json
  src/main/resources/assets/iris/lang/zh_tw.json
Labels: type: translations

#1197 Update zh_cn translations
  src/main/resources/assets/iris/lang/zh_cn.json
Labels: type: translations

#1191 Updated it_it.json (13 January 2022)
  src/main/resources/assets/iris/lang/it_it.json
Labels: type: translations

#1189 Update ko_kr translate
  src/main/resources/assets/iris/lang/ko_kr.json
Labels: type: translations

#1179 Update German translation
  src/main/resources/assets/iris/lang/de_de.json
Labels: type: translations

#1186 Update ru_ru.json
  src/main/resources/assets/iris/lang/ru_ru.json
Labels: type: translations

#1185 Bug Fixes and Improvements to the Shader Pack Option GUI
  src/main/java/net/coderbot/iris/Iris.java
  src/main/java/net/coderbot/iris/gui/FileDialogUtil.java
  src/main/java/net/coderbot/iris/gui/GuiUtil.java
  src/main/java/net/coderbot/iris/gui/NavigationController.java
  src/main/java/net/coderbot/iris/gui/element/IrisElementRow.java
  src/main/java/net/coderbot/iris/gui/element/ShaderPackOptionList.java
  src/main/java/net/coderbot/iris/gui/element/ShaderPackSelectionList.java
  src/main/java/net/coderbot/iris/gui/element/widget/BooleanElementWidget.java
  src/main/java/net/coderbot/iris/gui/element/widget/SliderElementWidget.java
  src/main/java/net/coderbot/iris/gui/screen/ShaderPackScreen.java
  src/main/java/net/coderbot/iris/shaderpack/ShaderPack.java
  src/main/java/net/coderbot/iris/shaderpack/option/values/MutableOptionValues.java
  src/main/resources/assets/iris/lang/en_us.json
  src/main/resources/assets/iris/textures/gui/widgets.png
Labels: status: waiting on author

#1220 Update pt_br.json - Shader config menu translations.
  src/main/resources/assets/iris/lang/pt_br.json
Labels: type: translations

#1206 Add perspective projection matrix support
  src/main/java/net/coderbot/iris/pipeline/ShadowRenderer.java
  src/main/java/net/coderbot/iris/shadow/ShadowMatrices.java
  src/main/java/net/coderbot/iris/shadows/ShadowRenderingState.java
Labels: status: waiting on review
