Repository IrisShaders/Iris, pull requests merged in 2022-02, with the labels that each got.

#1209 Update zh_tw.json
  src/main/resources/assets/iris/lang/zh_tw.json
Labels: type: translations, status: waiting on author

#1219 Update zh_cn translations
  src/main/resources/assets/iris/lang/zh_cn.json
Labels: type: translations

#1221 Create th_th.lang
  src/main/resources/assets/iris/lang/th_th.lang
Labels: type: translations

#1236 Update Czech language
  src/main/resources/assets/iris/lang/cs_cz.json
Labels: type: translations

#1246 Update Turkish language
  src/main/resources/assets/iris/lang/tr_tr.json
Labels: type: translations

#1254 Update sk_sk.json
  src/main/resources/assets/iris/lang/sk_sk.json
Labels: type: translations

#1280 Major shadow culling refractors, ability to contain separate frustums
  src/main/java/net/coderbot/iris/mixin/LevelRendererAccessor.java
  src/main/java/net/coderbot/iris/mixin/shadows/ChunkInfoAccessor.java
  src/main/java/net/coderbot/iris/mixin/shadows/MixinPreventRebuildNearInShadowPass.java
  src/main/java/net/coderbot/iris/pipeline/ShadowRenderer.java
  src/main/java/net/coderbot/iris/shaderpack/PackShadowDirectives.java
  src/main/java/net/coderbot/iris/shadows/frustum/FrustumHolder.java
  src/main/resources/iris.accesswidener
  src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/mixin/shadow_map/MixinSodiumWorldRenderer.java
Labels: status: waiting on review

#1257 Geometry shader support in vanilla 1.17!
  src/main/java/net/coderbot/iris/mixin/MixinGameRenderer.java
  src/main/java/net/coderbot/iris/mixin/MixinProgramManager.java
  src/main/java/net/coderbot/iris/mixin/MixinProgramType.java
  src/main/java/net/coderbot/iris/mixin/MixinShaderInstance.java
  src/main/java/net/coderbot/iris/mixin/ProgramTypeAccessor.java
  src/main/java/net/coderbot/iris/pipeline/newshader/ExtendedShader.java
  src/main/java/net/coderbot/iris/pipeline/newshader/IrisProgramTypes.java
  src/main/java/net/coderbot/iris/pipeline/newshader/NewShaderTests.java
  src/main/java/net/coderbot/iris/pipeline/newshader/ShaderInstanceInterface.java
  src/main/java/net/coderbot/iris/pipeline/newshader/TriforcePatcher.java
  src/main/java/net/coderbot/iris/postprocess/CompositeRenderer.java
  src/main/java/net/coderbot/iris/postprocess/FinalPassRenderer.java
  src/main/resources/mixins.iris.json
Labels: status: waiting on review

#1270 Fixes for Create (Fabric) / Flywheel
  src/main/java/net/coderbot/iris/mixin/LevelRendererAccessor.java
  src/main/java/net/coderbot/iris/pipeline/ShadowRenderer.java
  src/main/resources/iris.accesswidener
Labels: status: waiting on review

#1294 Remove un-used code in issue config
  .github/ISSUE_TEMPLATE/config.yml
Labels: status: waiting on review
