Repository IrisShaders/Iris, pull requests merged in 2022-04, with the labels that each got.

#1350 Add Ukrainian and update Russian translation
  src/main/resources/assets/iris/lang/ru_ru.json
  src/main/resources/assets/iris/lang/ua_ua.json
Labels: type: translations

#1328 Update German translation
  src/main/resources/assets/iris/lang/de_de.json
Labels: type: translations

#1335 Fixed translations to make the message more clear.
  src/main/resources/assets/iris/lang/pt_br.json
Labels: type: translations

#1334 Update Polish translation (pl_pl)
  src/main/resources/assets/iris/lang/pl_pl.json
Labels: type: translations

#1390 Block type map support
  src/main/java/net/coderbot/iris/block_rendering/BlockMaterialMapping.java
  src/main/java/net/coderbot/iris/block_rendering/BlockRenderingSettings.java
  src/main/java/net/coderbot/iris/mixin/MixinItemBlockRenderTypes.java
  src/main/java/net/coderbot/iris/pipeline/DeferredWorldRenderingPipeline.java
  src/main/resources/mixins.iris.json
Labels: unimplemented, status: waiting on review

#1374 Move HorizonRenderer to the pipeline package and don't create it every frame
  src/main/java/net/coderbot/iris/mixin/MixinLevelRenderer.java
  src/main/java/net/coderbot/iris/pipeline/HorizonRenderer.java
Labels: code quality

#1348 Update zh_cn.json
  src/main/resources/assets/iris/lang/zh_cn.json
Labels: type: translations
