Repository IrisShaders/Iris, pull requests merged in 2022-05, with the labels that each got.

#1322 Super Duper Vanilla support
  src/main/java/net/coderbot/iris/uniforms/HardcodedCustomUniforms.java
  src/main/java/net/coderbot/iris/uniforms/WorldTimeUniforms.java
Labels: status: waiting on review

#1400 Optimize atlas stitching
  src/main/java/net/coderbot/iris/mixin/optimized_stitching/MixinStitcher.java
  src/main/resources/fabric.mod.json
  src/main/resources/iris.accesswidener
  src/main/resources/mixins.iris.optimized-stitching.json
Labels: enhancement

#1410 GPU-based center depth sampling
  src/main/java/net/coderbot/iris/gl/texture/DepthBufferFormat.java
  src/main/java/net/coderbot/iris/pipeline/DeferredWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/pipeline/patcher/AttributeShaderTransformer.java
  src/main/java/net/coderbot/iris/pipeline/patcher/CompositeDepthTransformer.java
  src/main/java/net/coderbot/iris/postprocess/CenterDepthSampler.java
  src/main/java/net/coderbot/iris/postprocess/CompositeRenderer.java
  src/main/java/net/coderbot/iris/postprocess/FinalPassRenderer.java
  src/main/java/net/coderbot/iris/shaderpack/PackDirectives.java
Labels: status: waiting on review

#1432 thunderStrength Iris exclusive uniform (red phone wins again)
  src/main/java/net/coderbot/iris/uniforms/IrisExclusiveUniforms.java
Labels: enhancement, high priority

#1435 Update checker
  src/main/java/net/coderbot/iris/Iris.java
  src/main/java/net/coderbot/iris/UpdateChecker.java
  src/main/java/net/coderbot/iris/UpdateInfo.java
  src/main/java/net/coderbot/iris/config/IrisConfig.java
  src/main/java/net/coderbot/iris/gui/screen/ShaderPackScreen.java
  src/main/java/net/coderbot/iris/mixin/MixinClientPacketListener.java
  src/main/java/net/coderbot/iris/mixin/MixinWindow.java
  src/main/resources/mixins.iris.json
  src/main/resources/mixins.iris.optimized-stitching.json
Labels: enhancement

#1411 Update fi_fi.json
  src/main/resources/assets/iris/lang/fi_fi.json
Labels: status: waiting on review

#1464 Copy initial depth texture to any extra depth textures to ensure data is not invalid
  src/main/java/net/coderbot/iris/gl/IrisRenderSystem.java
  src/main/java/net/coderbot/iris/pipeline/FixedFunctionWorldRenderingPipeline.java
  src/main/java/net/coderbot/iris/rendertarget/DepthTexture.java
  src/main/java/net/coderbot/iris/rendertarget/RenderTargets.java
  src/main/java/net/coderbot/iris/shadows/ShadowRenderTargets.java
Labels: high priority
